[package]
name = "distributor"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "distributor"
path = "src/main.rs"

[dependencies]
utility = { path = "../utility" }
clap = { version = "4.0", features = ["derive"] }
