[package]
name = "node"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "node"
path = "src/main.rs"

[dependencies]
utility = { path = "../utility" }
num-traits = "0.2"
num-derive = "0.4" 
clap = { version = "4.0", features = ["derive"] }